"""
Tests for the charging queue model.

The queueing model is based on:

    t =
    (c(N) - 1) / (2k) * E[T] + t_0

where:

    c(N) = number of EVs choosing to charge
    k    = number of charging piles
    E[T] = expected charging time
    t_0  = existing queueing time
"""


import pytest

from charging_station import ChargingStation
from queue_model import calculate_queue_time


# ---------------------------------------------------------------------
# Test 1: Basic Queueing Time
# ---------------------------------------------------------------------

def test_basic_queue_time():
    """
    Test the basic queueing-time formula.

    Example:

        3 EVs
        4 charging piles

        Charging energies:
            20 kWh
            40 kWh
            60 kWh

        Charging power = 50 kW

    Charging times:

        20 / 50 = 0.40 h
        40 / 50 = 0.80 h
        60 / 50 = 1.20 h

    Expected charging time:

        E[T] = (0.40 + 0.80 + 1.20) / 3
             = 0.80 h

    Queueing time:

        t = (3 - 1) / (2 * 4) * 0.80
          = 0.20 h
    """

    station = ChargingStation(
        charging_power=50.0,
        electricity_price=0.30,
        num_piles=4
    )

    charging_energies = [
        20.0,
        40.0,
        60.0
    ]

    queue_time = calculate_queue_time(
        num_charging_evs=3,
        charging_station=station,
        charging_energies=charging_energies,
        existing_queue_time=0.0
    )

    assert queue_time == pytest.approx(0.20)


# ---------------------------------------------------------------------
# Test 2: No Queue When Only One EV Charges
# ---------------------------------------------------------------------

def test_no_queue_for_single_ev():
    """
    If only one EV chooses to charge, there should be
    no strategic queue generated by other charging EVs.

    Formula:

        (1 - 1) / (2k) * E[T] = 0
    """

    station = ChargingStation(
        charging_power=50.0,
        electricity_price=0.30,
        num_piles=4
    )

    charging_energies = [
        40.0
    ]

    queue_time = calculate_queue_time(
        num_charging_evs=1,
        charging_station=station,
        charging_energies=charging_energies,
        existing_queue_time=0.0
    )

    assert queue_time == pytest.approx(0.0)


# ---------------------------------------------------------------------
# Test 3: Existing Queue Time
# ---------------------------------------------------------------------

def test_existing_queue_time():
    """
    Existing queueing time should be added to the
    strategic queueing component.

    Example:

        Strategic queue = 0.20 h
        Existing queue  = 0.10 h

        Total queue = 0.30 h
    """

    station = ChargingStation(
        charging_power=50.0,
        electricity_price=0.30,
        num_piles=4
    )

    charging_energies = [
        20.0,
        40.0,
        60.0
    ]

    queue_time = calculate_queue_time(
        num_charging_evs=3,
        charging_station=station,
        charging_energies=charging_energies,
        existing_queue_time=0.10
    )

    assert queue_time == pytest.approx(0.30)


# ---------------------------------------------------------------------
# Test 4: More EVs Increase Queueing Time
# ---------------------------------------------------------------------

def test_more_evs_increase_queue_time():
    """
    Holding charging capacity constant, increasing the
    number of charging EVs should increase queueing time.
    """

    station = ChargingStation(
        charging_power=50.0,
        electricity_price=0.30,
        num_piles=2
    )

    queue_two_evs = calculate_queue_time(
        num_charging_evs=2,
        charging_station=station,
        charging_energies=[
            40.0,
            40.0
        ],
        existing_queue_time=0.0
    )

    queue_four_evs = calculate_queue_time(
        num_charging_evs=4,
        charging_station=station,
        charging_energies=[
            40.0,
            40.0,
            40.0,
            40.0
        ],
        existing_queue_time=0.0
    )

    assert queue_four_evs > queue_two_evs


# ---------------------------------------------------------------------
# Test 5: More Charging Piles Reduce Queueing Time
# ---------------------------------------------------------------------

def test_more_piles_reduce_queue_time():
    """
    Holding the number of charging EVs and charging
    energy constant, increasing the number of charging
    piles should reduce queueing time.
    """

    station_two_piles = ChargingStation(
        charging_power=50.0,
        electricity_price=0.30,
        num_piles=2
    )

    station_four_piles = ChargingStation(
        charging_power=50.0,
        electricity_price=0.30,
        num_piles=4
    )

    charging_energies = [
        40.0,
        40.0,
        40.0,
        40.0
    ]

    queue_two_piles = calculate_queue_time(
        num_charging_evs=4,
        charging_station=station_two_piles,
        charging_energies=charging_energies,
        existing_queue_time=0.0
    )

    queue_four_piles = calculate_queue_time(
        num_charging_evs=4,
        charging_station=station_four_piles,
        charging_energies=charging_energies,
        existing_queue_time=0.0
    )

    assert queue_four_piles < queue_two_piles


# ---------------------------------------------------------------------
# Test 6: Zero EVs
# ---------------------------------------------------------------------

def test_zero_charging_evs():
    """
    If no EV chooses to charge, the queueing time should
    be zero when there is no existing queue.
    """

    station = ChargingStation(
        charging_power=50.0,
        electricity_price=0.30,
        num_piles=4
    )

    queue_time = calculate_queue_time(
        num_charging_evs=0,
        charging_station=station,
        charging_energies=[],
        existing_queue_time=0.0
    )

    assert queue_time == pytest.approx(0.0)


# ---------------------------------------------------------------------
# Test 7: Invalid Number of Piles
# ---------------------------------------------------------------------

def test_invalid_number_of_piles():
    """
    The number of charging piles must be positive.
    """

    with pytest.raises(ValueError):

        ChargingStation(
            charging_power=50.0,
            electricity_price=0.30,
            num_piles=0
        )


# ---------------------------------------------------------------------
# Test 8: Negative Existing Queue
# ---------------------------------------------------------------------

def test_negative_existing_queue():
    """
    Existing queueing time cannot be negative.
    """

    station = ChargingStation(
        charging_power=50.0,
        electricity_price=0.30,
        num_piles=4
    )

    with pytest.raises(ValueError):

        calculate_queue_time(
            num_charging_evs=3,
            charging_station=station,
            charging_energies=[
                20.0,
                40.0,
                60.0
            ],
            existing_queue_time=-0.10
        )
